Support serialize and deserialize nested custom types
sindresorhus/Defaults pull request #118
Opened 2022-10-19 10:20 UTC by hank121314

## Summary

This PR fixes: #101.

`Defaults` now support serializing and deserializing nested custom types.

## Thanks

Thanks for your code review 😄 !

2022-10-27 09:55 UTC, sindresorhus requested changes

2022-10-27 09:55 UTC, sindresorhus commented on Tests/DefaultsTests/DefaultsCustomBridgeTests.swift
> +		XCTAssertEqual(rawValue, ["{\"minute\":0,\"hour\":1}", "{\"minute\":0,\"hour\":2}"])
You can use `#"x"#` string to avoid the escaping.

2022-10-27 09:56 UTC, sindresorhus commented
Thanks for fixing this. Do you plan more changes after this PR? If not, I will make a release.

2022-10-28 07:58 UTC, hank121314 commented
> Do you plan more changes after this PR?

I would like to move on to #108.
But I think this feature might be useful, maybe it is worth to make a minor release?

2022-10-28 08:26 UTC, sindresorhus commented
> maybe it is worth to make a minor release?

Ah, then it's no rush. We can wait until after that. Another reason to wait a little bit more is that the release would require Xcode 14.1.

2022-10-28 08:27 UTC, merged

2022-10-28 10:17 UTC, hank121314 commented
> Ah, then it's no rush. We can wait until after that. Another reason to wait a little bit more is that the release would require Xcode 14.1.

Got it! That makes sense. Thanks for the explanation!