Validate the default key name and emit with Xcode runtime warning
sindresorhus/Defaults pull request #126
Opened 2022-12-02 10:37 UTC by hank121314

## Summary

1. Implement Xcode runtime warning in `Defaults`.
   In order to let `Defaults.Key.init` support `@_alwaysEmitIntoClient`, 
   there is a needed to mark some functions/properties as `@usableFromInline`. 
   And I also explicit the `internal` keyword for these functions/properties(To remind the developer not to change the access level).

2. Validate the default key name and if it is wrong, emit with Xcode runtime warning.

## Screenshot

<img width="1440" alt="screenshot-xcode-runtime-warning" src="https://user-images.githubusercontent.com/17615229/205273279-3cf4b56f-0b34-48f2-84d8-127ff3734ce8.png">

## Thanks

Thanks for your code review 😄 !

2022-12-03 20:09 UTC, sindresorhus requested changes

2022-12-03 20:09 UTC, sindresorhus commented on Sources/Defaults/Utilities.swift
> +			return asciiValue != 46
I think `{ $0 != "." && $0.isASCII }` would be simpler.

2022-12-03 20:09 UTC, sindresorhus commented on Sources/Defaults/Utilities.swift
> +internal let dynamicSharedObject = { () -> UnsafeMutableRawPointer in
```suggestion
internal let dynamicSharedObject: UnsafeMutableRawPointer = {
```

2022-12-03 20:10 UTC, sindresorhus commented
> In order to let Defaults.Key.init support @_alwaysEmitIntoClient,

Why does `Defaults.Key.init` need to support `@_alwaysEmitIntoClient`?

2022-12-04 13:03 UTC, hank121314 commented
> Why does Defaults.Key.init need to support @_alwaysEmitIntoClient?

With `@_alwaysEmitIntoClient`, it will let runtime warning appear at call site.

Here is the screenshot if not using `@_alwaysEmitIntoClient`:

<img width="1440" alt="screenshot-without-alwaysEmitIntoClient" src="https://user-images.githubusercontent.com/17615229/205492000-b9b338b5-6553-4304-a718-20a7c15e7894.png">

2022-12-12 17:17 UTC, merged

2022-12-12 17:17 UTC, sindresorhus commented
Nice work 👍